<a href="https://colab.research.google.com/github/TAUSEEF-01/GClab/blob/main/00_learing_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello world!")

Hello world!


In [2]:
!nvidia-smi

Sun Mar 16 19:32:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 5, 6],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 6],
         [2, 4, 5]]])

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [2, 4, 5]])

In [27]:
TENSOR[0][1]

tensor([3, 5, 6])

In [28]:
TENSOR[0][1][2]

tensor(6)

In [33]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.0689, 0.3377, 0.1855, 0.1438, 0.9699],
        [0.5239, 0.5792, 0.2627, 0.5242, 0.5317],
        [0.6716, 0.3043, 0.2829, 0.0972, 0.3527]])

In [37]:
random_tensor.ndim

2

In [38]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)